// upload thesis contants
export const UPLOAD_THESIS_PREV = "UPLOAD_THESIS_PREV";
export const UPLOAD_THESIS_NEXT = "UPLOAD_THESIS_NEXT";
export const SHOW_SELECTED_UPLOAD_FORM = "SHOW_SELECTED_UPLOAD_FORM";
export const SET_INSTITUTION_INFO_INPUT = "SET_INSTITUTION_INFO_INPUT";
export const SET_AUTHOR_INFO_INPUT = "SET_AUTHOR_INFO_INPUT";
export const SET_THESIS_INFO_INPUT = "SET_THESIS_INFO_INPUT";
export const SET_UPLOAD_INFO_INPUT = "SET_UPLOAD_INFO_INPUT";
export const CONFIRM_THESIS_UPLOAD = "CONFIRM_THESIS_UPLOAD";

// search document constants
export const SET_SEARCH_DOC_INPUT = "SET_SEARCH_DOC_INPUT";
